### ISSUE TITLE
Add exclude option to repo

### ISSUE THREAD

**Issue by teluq-pbrideau** [bp85/puppet-mirror_repos#13]
I’m trying to mirror the gitlab repository but it is very big, i want to mirror only versions I intend to use in my infrastructure.

There is an option to exclude package from `reposync`, just add `exclude=GLOB` in the config file
```puppet
class example {
  $repo = {
    'gitlab' => {
      'el8' => {
        'baseurl' => 'https://packages.gitlab.com/gitlab/gitlab-ce/el/8/x86_64/',
        'gpgkey'  => 'https://packages.gitlab.com/gpg.key',
        'enabled' => 1,
        'exclude' => [
          'gitlab-ce-12*',
          'gitlab-ce-13*',
          'gitlab-ce-14*',
        ],
      },
    },
  }
  class { 'mirror_repos' :
    repos => $repo,
    [...]
   }
}
```

I’ve made a branch with the fix on my fork:
https://github.com/teluq-pbrideau/puppet-mirror_repos/tree/feat-exclude

but it requires the template to be converted to `epp`, so is dependent on other changes I made in PR #7

Once you decide if you want to integrate my changes, i’ll open PR with this change

**Comment by bp85** [comment]
Resolved via #14
