### ISSUE TITLE
Problem sed and update-repos.sh script

### ISSUE THREAD

**Issue by jsmelser** [bp85/puppet-mirror_repos#2]
Sed seems to be missing the g on it. sed/-/_/. This fails for redhat since they tend to have multiple - in them.

**Comment by bp85** [comment]
Hi @jsmelser ,

Yeah, when I initially wrote it, I never had any reason to replace more than one -, so missed it.
https://github.com/bp85/puppet-mirror_repos/pull/3 is the fix.
Once merged the new version will be published to puppetforge

Bhanu
